/**
 * scripts/ebay-deletion-setup.ts — prepare eBay's account-deletion subscription.
 *
 *   npx tsx scripts/ebay-deletion-setup.ts https://your-site.example
 *
 * Writes EBAY_DELETION_ENDPOINT (<site>/api/ebay/account-deletion) and a fresh
 * EBAY_VERIFICATION_TOKEN to .env.local, then prints both: they go into eBay's
 * developer portal (Alerts & Notifications -> Marketplace account deletion).
 * The token only proves this endpoint is yours to eBay; it isn't a key to
 * anything. Refuses to replace an existing token, since eBay would then fail
 * the challenge until the portal is updated too.
 *
 * Then restart the server, and use "Send Test Notification" in the portal.
 */

import { readFileSync, appendFileSync, existsSync } from "fs";
import { randomBytes } from "crypto";

function main() {
  const site = process.argv[2]?.trim().replace(/\/+$/, "");
  if (!site || !/^https:\/\/[^/]+/.test(site)) {
    throw new Error("Pass the site's public https address, e.g. https://sigpath.example — eBay only calls https endpoints.");
  }
  const path = ".env.local";
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (/^EBAY_VERIFICATION_TOKEN=/m.test(current)) {
    throw new Error("EBAY_VERIFICATION_TOKEN already exists in .env.local. Change it by hand, and update eBay's portal to match.");
  }
  const endpoint = `${site}/api/ebay/account-deletion`;
  const token = randomBytes(36).toString("base64url").slice(0, 48); // eBay: 32-80 of [A-Za-z0-9_-]
  const sep = current && !current.endsWith("\n") ? "\n" : "";
  appendFileSync(path, `${sep}\n# eBay account-deletion subscription. Generated by scripts/ebay-deletion-setup.ts.\nEBAY_DELETION_ENDPOINT=${endpoint}\nEBAY_VERIFICATION_TOKEN=${token}\n`, { mode: 0o600 });
  console.log("Added to .env.local. Enter these in eBay's developer portal");
  console.log("(Alerts & Notifications -> Marketplace account deletion):\n");
  console.log(`  Endpoint:            ${endpoint}`);
  console.log(`  Verification token:  ${token}\n`);
  console.log("Restart the server, then click Send Test Notification in the portal.");
}

try {
  main();
} catch (e) {
  console.error("ERROR:", e instanceof Error ? e.message : e);
  process.exit(1);
}
