/**
 * scripts/vapid-keys.ts — create the Web Push (VAPID) keys for price alerts.
 *
 *   npx tsx scripts/vapid-keys.ts
 *
 * Appends VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY to .env.local, and prints
 * only the PUBLIC key. Refuses if keys already exist: replacing them silently
 * breaks every existing alert, because browsers subscribed to the old key.
 */

import { readFileSync, appendFileSync, existsSync } from "fs";

async function main() {
  const { generateVapidKeys } = await import("../lib/alerts/push");
  const path = ".env.local";
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (/^VAPID_(PUBLIC|PRIVATE)_KEY=/m.test(current)) {
    throw new Error("VAPID keys already exist in .env.local. Replacing them breaks every existing alert — delete them by hand first if you really mean to.");
  }
  const k = generateVapidKeys();
  const sep = current && !current.endsWith("\n") ? "\n" : "";
  appendFileSync(path, `${sep}\n# Web Push (price alerts). Generated by scripts/vapid-keys.ts.\nVAPID_PUBLIC_KEY=${k.publicKey}\nVAPID_PRIVATE_KEY=${k.privateKey}\n`, { mode: 0o600 });
  console.log(`Added VAPID keys to ${path}. Public key: ${k.publicKey}`);
  console.log("Restart the dev server to pick them up.");
}

main().catch((e) => {
  console.error("ERROR:", e instanceof Error ? e.message : e);
  process.exit(1);
});
